version: "3"
services:
  wiki:
    image: requarks/wiki:beta
    environment:
      DB_TYPE: postgres
      DB_HOST: web.jank
      DB_PORT: 5432
      DB_USER: luricidex
      DB_PASS: hellotoday
      DB_NAME: wiki
    ports:
      - "82:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example
